name: Build Couchbase 2.6.2 Images

on:
  push:
    branches:
      - 2.6.2
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-22.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./dockerfiles/${{ github.ref_name }}/
          platforms: linux/amd64
          push: true
          tags: deminy/php-couchbase:${{ github.ref_name }}
