name: Build Couchbase 3.2.2 Images

on:
  push:
    branches:
      - 3.2.2
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - {php: "7.4", "swoole": "4.8"}
          - {php: "8.0", "swoole": "5.1"}
          - {php: "8.1", "swoole": "5.1"}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Images of PHP ${{ matrix.env.php }} + Swoole ${{ matrix.env.swoole }}
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./dockerfiles/${{ github.ref_name }}/
          build-args: |
            SWOOLE_IMAGE_TAG=${{ matrix.env.swoole }}-php${{ matrix.env.php }}
            LIBCOUCHBASE_VERSION=3.3.17
          platforms: linux/amd64
          push: true
          tags: deminy/php-couchbase:${{ github.ref_name }}-php${{ matrix.env.php }}
