name: Build Couchbase 4 Images

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'
      - '[4-9].[0-9]+.[0-9]+-?[a-zA-Z]**'
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - {version: "8.0", "ext_dir": "no-debug-non-zts-20200930"}
          - {version: "8.1", "ext_dir": "no-debug-non-zts-20210902"}
          - {version: "8.2", "ext_dir": "no-debug-non-zts-20220829"}
          - {version: "8.3", "ext_dir": "no-debug-non-zts-20230831"}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Images of PHP ${{ matrix.php.version }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/4.1.x/
          build-args: |
            SWOOLE_IMAGE_TAG=5.1-php${{ matrix.php.version }}
            COUCHBASE_VERSION=${{ github.ref_name }}
            PHP_EXTENSION_DIR=${{ matrix.php.ext_dir }}
          platforms: linux/amd64
          push: true
          tags: deminy/php-couchbase:${{ github.ref_name }}-php${{ matrix.php.version }}

      -
        name: Image Digest of deminy/php-couchbase:${{ github.ref_name }}-php${{ matrix.php.version }}
        run: echo ${{ steps.docker_build.outputs.digest }}
